### ISSUE TITLE
Some suggestions on GAP package best practices

### ISSUE THREAD

**Issue by fingolfin** [dylanpeifer/difsets#2]
Some suggestions based on experience with maintaining a couple dozen packages, and collaboration with the majority of GAP package authors on these matters: You may wish to adopt a few tools and best practices that we developed. In particular, please consider using/doing these things:

- Setup a proper website for your package using https://github.com/gap-system/GitHubPagesForGAP (this is a matter of a few minutes work, just follow the instructions)
- Afterwards, you can use https://github.com/gap-system/ReleaseTools to simplify future releases of your package -- this tool has saved dozens of package authors hours and hours of work, by removing tedious repetition and catching many common errors
- remove all the generated files from the repository (so the `doc/chap*` files, LaTeX temporary files etc.)
- adopt https://github.com/gap-packages/AutoDoc for your `makedoc.g`. It can also generate the XML for the title page of your package manual from the `PackageInfo.g` file, thus ensuring it always contains the correct version and release date, package subtitle, your address etc.
- set up continuous integration tests and code coverage, by using https://github.com/gap-system/pkg-ci-scripts (unfortunately, we still need to write instructions for that, but it's not hard and if you are interested, me and @alex-konovalov can help)

**Comment by fingolfin** [comment]
I just learned that you actually are using GitHubPagesForGAP, which is good -- but to make it easy to find from the repository page at https://github.com/dylanpeifer/difsets, I recommend to set the repository website to the matching URL, i.e., https://dylanpeifer.github.io/difsets/ -- in case you are not familiar with this, here is a brief animation showing how to do that: https://stackoverflow.com/a/21649064

**Comment by dylanpeifer** [comment]
I've implemented all of these changes. Thanks for the suggestions!
